---
- name: Realizar validaciones de Windows
  hosts: all

  tasks:
  - name: Revisar los servicios activos
    ansible.windows.win_shell: Get-Service | Where-Object {$_.Status -eq "Running"}
    register: servicios

  - name: informe los servicios habilitados
    ansible.builtin.debug:
      var: servicios.stdout_lines

  - name: Revisar los Procesos activos
    ansible.windows.win_shell: Get-Process
    register: procesos

  - name: informe los Procesos en ejecucion
    ansible.builtin.debug:
      var: procesos.stdout_lines

#  - name: Obtener valores de los discos
#    community.windows.win_disk_facts:


  - name: "Comprobar espacio libre en C:"
    ansible.windows.win_shell: "write-host ([math]::Round((Get-PSDrive C | Select-Object Free).free / 1024 / 1024 / 1024,2))"
    register: freespace

  - name: informe de espacio libre en disco
    ansible.builtin.debug:
      msg: |
          "Tamaño disponible del disco {{ freespace.stdout }} GB"

  - name: Tamaño total del disco
    ansible.builtin.debug:
      msg: "Tamaño total del disco C: es {{ disksize_gb }} y le quedan libres {{ freespace.stdout }} GB"
    vars:
      disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
      disksize_gb: '{{ (disk.size/1000|pow(3))|round|int }} GB'  # returns "240 GB" (value in GB)
